/*
 * WarrantInfoPage.java
 *
 * Created on December 6, 2013, 1:51 PM
 */

package com.rameses.gov.police.datamgmt;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  rameses
 */
@StyleSheet
@Template(FormPage.class)
public class WarrantInfoPage extends javax.swing.JPanel 
{
    public WarrantInfoPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        formPanel3 = new com.rameses.rcp.util.FormPanel();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        formPanel4 = new com.rameses.rcp.util.FormPanel();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xTextField6 = new com.rameses.rcp.control.XTextField();
        xTextField7 = new com.rameses.rcp.control.XTextField();
        xTextField8 = new com.rameses.rcp.control.XTextField();
        xTextField9 = new com.rameses.rcp.control.XTextField();
        xTextField10 = new com.rameses.rcp.control.XTextField();

        jPanel1.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("  Warrant Information   ");
        jPanel1.setBorder(xTitledBorder1);

        formPanel3.setPreferredSize(new java.awt.Dimension(74, 45));
        xDateField1.setCaption("Date Issued");
        xDateField1.setCaptionWidth(110);
        xDateField1.setIndex(-1);
        xDateField1.setName("entity.dtissued");
        xDateField1.setOutputFormat("MMM-dd-yyyy");
        xDateField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xDateField1.setRequired(true);
        formPanel3.add(xDateField1);

        xTextField2.setCaption("Crime Case No.");
        xTextField2.setCaptionWidth(110);
        xTextField2.setName("entity.crimecaseno");
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField2.setRequired(true);
        formPanel3.add(xTextField2);

        jPanel1.add(formPanel3);
        formPanel3.setBounds(10, 20, 300, 50);

        formPanel2.setPadding(new java.awt.Insets(5, 5, 5, 0));
        xComboBox1.setAllowNull(false);
        xComboBox1.setCaption("Status");
        xComboBox1.setExpression("#{item.value}");
        xComboBox1.setItemKey("key");
        xComboBox1.setItems("statusList");
        xComboBox1.setName("entity.state");
        xComboBox1.setPreferredSize(new java.awt.Dimension(0, 22));
        xComboBox1.setRequired(true);
        formPanel2.add(xComboBox1);

        xDecimalField1.setCaption("Bail Amount");
        xDecimalField1.setCaptionWidth(80);
        xDecimalField1.setFont(new java.awt.Font("Tahoma", 0, 11));
        xDecimalField1.setName("entity.bailamount");
        xDecimalField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xDecimalField1.setRequired(true);
        formPanel2.add(xDecimalField1);

        jPanel1.add(formPanel2);
        formPanel2.setBounds(310, 20, 240, 54);

        formPanel4.setPadding(new java.awt.Insets(5, 5, 5, 0));
        xTextField5.setCaption("Crime Case");
        xTextField5.setCaptionWidth(110);
        xTextField5.setName("entity.crimecasedesc");
        xTextField5.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField5.setRequired(true);
        formPanel4.add(xTextField5);

        xTextField3.setCaption("Name of Court");
        xTextField3.setCaptionWidth(110);
        xTextField3.setName("entity.courtname");
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField3.setRequired(true);
        formPanel4.add(xTextField3);

        xTextField4.setCaption("Name of Judge");
        xTextField4.setCaptionWidth(110);
        xTextField4.setName("entity.judgename");
        xTextField4.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField4.setRequired(true);
        formPanel4.add(xTextField4);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 60));
        xTextArea1.setCaption("Remarks");
        xTextArea1.setCaptionWidth(110);
        xTextArea1.setName("entity.remarks");
        xTextArea1.setPreferredSize(new java.awt.Dimension(0, 58));
        xTextArea1.setTextCase(com.rameses.rcp.constant.TextCase.UPPER);
        jScrollPane1.setViewportView(xTextArea1);

        formPanel4.add(jScrollPane1);

        jPanel1.add(formPanel4);
        formPanel4.setBounds(10, 69, 540, 140);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("  Accussed Information   ");
        formPanel1.setBorder(xTitledBorder2);
        formPanel1.setPadding(new java.awt.Insets(5, 15, 5, 50));
        xTextField6.setCaption("Last Name");
        xTextField6.setCaptionWidth(110);
        xTextField6.setName("entity.lastname");
        xTextField6.setPreferredSize(new java.awt.Dimension(180, 20));
        xTextField6.setRequired(true);
        formPanel1.add(xTextField6);

        xTextField7.setCaption("First Name");
        xTextField7.setCaptionWidth(110);
        xTextField7.setName("entity.firstname");
        xTextField7.setPreferredSize(new java.awt.Dimension(180, 20));
        xTextField7.setRequired(true);
        formPanel1.add(xTextField7);

        xTextField8.setCaption("Middle Name");
        xTextField8.setCaptionWidth(110);
        xTextField8.setName("entity.middlename");
        xTextField8.setPreferredSize(new java.awt.Dimension(180, 20));
        formPanel1.add(xTextField8);

        xTextField9.setCaption("Alias");
        xTextField9.setCaptionWidth(110);
        xTextField9.setName("entity.alias");
        xTextField9.setPreferredSize(new java.awt.Dimension(0, 20));
        formPanel1.add(xTextField9);

        xTextField10.setCaption("Address");
        xTextField10.setCaptionWidth(110);
        xTextField10.setName("entity.address");
        xTextField10.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField10.setRequired(true);
        formPanel1.add(xTextField10);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 600, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 600, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 221, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel2;
    private com.rameses.rcp.util.FormPanel formPanel3;
    private com.rameses.rcp.util.FormPanel formPanel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    private com.rameses.rcp.control.XTextField xTextField10;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField6;
    private com.rameses.rcp.control.XTextField xTextField7;
    private com.rameses.rcp.control.XTextField xTextField8;
    private com.rameses.rcp.control.XTextField xTextField9;
    // End of variables declaration//GEN-END:variables
    
}
